services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
      - "5173:5173"
    volumes:
      - ./server/database:/app/server/database
    restart: unless-stopped

