
# services:
#   backend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#       target: backend
#     env_file:
#       - server/.env
#     volumes:
#       - ./server:/app/server:cached
#       - ./shared:/app/shared:cached
#       - /app/server/node_modules
#     working_dir: /app/server
#     ports:
#       - "3000:3000"

#   frontend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#       target: frontend
#     env_file:
#       - server/.env
#     volumes:
#       - ./client:/app/client:cached
#       - ./shared:/app/shared:cached
#       - ./server/cert:/app/server/cert:cached
#       - /app/client/node_modules
#     working_dir: /app/client
#     ports:
#       - "5173:5173"




services:
  backend:
    build:
      context: .              # корень проекта, где ищем Dockerfile
      dockerfile: Dockerfile
      target: backend
    env_file:
      - server/.env           # подтянет PORT, JWT_SECRET_KEY и VITE_API_URL
    environment:
      - PORT=3000             # явно пробрасываем
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./server:/app/server:cached
      - ./shared:/app/shared:cached
      - server_node_modules:/app/server/node_modules
    working_dir: /app/server
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    env_file:
      - server/.env           # оттуда подхватит VITE_API_URL=https://localhost:3000
    environment:
      - VITE_API_URL          # гарантируем, что Vite его увидит
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./client:/app/client:cached
      - ./shared:/app/shared:cached
      - ./server/cert:/app/server/cert:cached
      - client_node_modules:/app/client/node_modules
    working_dir: /app/client
    ports:
      - "5173:5173"

volumes:
  server_node_modules: {}      # именованные тома для node_modules
  client_node_modules: {}
