# syntax=docker/dockerfile:1

FROM node:18-slim AS base

WORKDIR /app

COPY package.json package-lock.json ./

# 1) backend

FROM base AS backend

#Install openssl for generating self-signed certificates
RUN apt-get update \
 && apt-get install -y --no-install-recommends openssl \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app/server

COPY server/package.json server/package-lock.json ./

RUN npm ci

COPY server/      ./
COPY ../shared    /app/shared

# Add entrypoint script that will generate certs at container start
COPY entrypoint.sh /app/entrypoint.sh

RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]
EXPOSE 3000
CMD ["npm", "run", "dev"]


# 2) frontend (dev) — с Vite & certs из backend

FROM base AS frontend

WORKDIR /app/client

COPY client/package.json client/package-lock.json ./

RUN npm ci

# код + shared
COPY client/         ./
COPY ../shared       /app/shared

# Bring in the self-signed certs generated by the backend stage
COPY --from=backend /app/server/cert /app/server/cert

RUN find src -type f -name '*.test.ts*' -delete

EXPOSE 5173

# Start Vite in dev mode; --host 0.0.0.0 exposes it to the host network
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
